---
title: "Methylation EDA"
subtitle: "Sen Lab - University of Michigan"
author: TingTing Lu
date: October 04, 2014
output: ioslides_presentation
---
```{r, include=FALSE}
## take care of front matters such as set path, load data and libraries and etc

proj.path = file.path(Sys.getenv("HOME"), "project-github/methyl")
source(file.path(proj.path, "multiplot.R"))
load(file.path(proj.path, "genelist.rdat"))
load(file.path(proj.path, "autox.sub.both.long.rdata"))
load(file.path(proj.path, "baselinecov.rdata"))

library(ggplot2)
library(knitr)
txt.angle = 15
```

## Methylation Data

- Number of unique Genes  : 23,369
- Number of total CpG Sites : 481,178
- Number of selected Genes : 25
- NUmber of selcted CpG Sites : 828

## List of Selected Genes 

```{r, echo=FALSE, results = "asis"}
gene <- genelist[1:6, ]
rownames(gene) <- NULL
kable(gene)
```

----

```{r, echo=FALSE, results = "asis"}
gene <- genelist[7:12, ]
rownames(gene) <- NULL
kable(gene)
```

----

```{r, echo=FALSE, results = "asis"}
gene <- genelist[13:18, ]
rownames(gene) <- NULL
kable(gene)
```

----

```{r, echo=FALSE, results = "asis"}
gene <- genelist[19:25, ]
rownames(gene) <- NULL
kable(gene)
```

```{r, echo=FALSE}
baselinecov$Specialty = gsub("\\/", " ", baselinecov$Specialty)
```

## Baseline Stationary Covariates {.smaller .columns-2}

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Sex + Cohort, baselinecov), format="pandoc", 
      caption="Gender by Cohort")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Sex + Age, baselinecov), format="pandoc", caption="Gender by Age")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Sex + Ethnicity, baselinecov), format="pandoc", 
      caption="Gender by Ethnicity")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Sex + Marital, baselinecov), format="pandoc", 
      caption="Gender by Marital Status")
```

## {.smaller}

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Sex + Child, baselinecov), format="pandoc", 
      caption="Gender by Child Status")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Sex + InstitutionID, baselinecov), format="pandoc", 
      caption="Gender by Institution")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Sex + Specialty, baselinecov), format="pandoc",
      caption="Gender by Specialty")
```

## {.smaller .columns-2}

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Cohort+ Age, baselinecov), format="pandoc", 
      caption="Cohort by Age")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Cohort + Ethnicity, baselinecov), format="pandoc", 
      caption="Cohort by Ethnicity")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Cohort + Marital, baselinecov), format="pandoc", 
      caption="Cohort by Marital Status")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Cohort + Child, baselinecov), format="pandoc", 
      caption="Cohort by Child Status")
```

## {.smaller}

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Cohort + InstitutionID, baselinecov), format="pandoc", 
      caption="Cohort by Institution")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Cohort + Specialty, baselinecov), format="pandoc", 
      caption="Cohort by Specialty")
```

## {.smaller .columns-2}

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Age + Marital, baselinecov), format="pandoc", 
      caption="Age by Marital Status")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Age + Child, baselinecov), format="pandoc", 
      caption="Age by Child Status")
```

## {.smaller}

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Age + Ethnicity, baselinecov), format="pandoc", 
      caption="Age by Ethnicity")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Age + InstitutionID, baselinecov), format="pandoc", 
      caption="Age by Institution")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Age + Specialty, baselinecov), format="pandoc", 
      caption="Age by Speciality")
```

## {.smaller .columns-2}

```{r, echo = FALSE, results="asis"}
kable(xtabs(~ Ethnicity + Marital, baselinecov), format="pandoc", 
      caption="Ethnicity by Marial Status")
```

```{r, echo=FALSE, comment=NA}
tb = with(baselinecov, table(Ethnicity, Marital))
pval = round(fisher.test(tb)$p.value, 3)
cat(paste0("p-value: ", pval))
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Ethnicity + Child, baselinecov), format="pandoc", 
      caption="Ethnicity by Child Status")
```

- jhkhkjhlk

## {.smaller}

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Ethnicity + InstitutionID, baselinecov), format="pandoc", 
      caption="Ethnicity by Institution")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Ethnicity + Specialty, baselinecov), format="pandoc", 
      caption="Ethnicity by Speciality")
```

## {.smaller}

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Marital + Child, baselinecov), format="pandoc", 
      caption="Marital Status by Child Status")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Marital + InstitutionID, baselinecov), format="pandoc", 
      caption="Marital Status by Institution")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Marital + Specialty, baselinecov), format="pandoc", 
      caption="Marital Status by Speciality")
```

## {.smaller}

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Child + InstitutionID, baselinecov), format="pandoc", 
      caption="Child Status by Institution")
```

```{r, echo=FALSE, results="asis"}
kable(xtabs(~ Child + Specialty, baselinecov), format="pandoc", 
      caption="Child Status by Speciality")
```

## Early Family Experience (EFE0)

```{r, echo=FALSE, warning=FALSE, message=FALSE}
baselinecov[] = lapply(baselinecov, 
                       function(x) if(is.character(x)) factor(x) else x)
baselinecov$Cohort = factor(baselinecov$Cohort)

p1 = ggplot(baselinecov, aes(x=Sex, y=EFE0, fill=Sex)) + geom_boxplot() +
        guides(fill=FALSE) + 
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)
p2 = ggplot(baselinecov, aes(x=Cohort, y=EFE0, fill=Cohort)) + geom_boxplot() +
        guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)
p3 = ggplot(baselinecov, aes(x=Age, y=EFE0, fill=Age)) + geom_boxplot() +
        guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)
p4 = ggplot(baselinecov, aes(x=Ethnicity, y=EFE0, fill=Ethnicity)) + 
        geom_boxplot() + guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)
multiplot(p1, p2, p3, p4, cols=2)
```

----

```{r echo=FALSE, warning=FALSE}
p1 = ggplot(baselinecov, aes(x=Specialty, y=EFE0, fill=Specialty)) + 
        geom_boxplot() + guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2) +
        theme(axis.text.x = element_text(angle = txt.angle))
p2 = ggplot(baselinecov, aes(x=Marital, y=EFE0, fill=Marital)) + 
        geom_boxplot() + guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)
p3 = ggplot(baselinecov, aes(x=Child, y=EFE0, fill=Child)) + geom_boxplot() +
        guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)

pushViewport(viewport(layout = grid.layout(2, 2)))  
print(p2, vp = viewport(layout.pos.row = 1, layout.pos.col = 1))     
print(p3, vp = viewport(layout.pos.row = 1, layout.pos.col = 2))     
print(p1, vp = viewport(layout.pos.row = 2, layout.pos.col = 1:2))
```

## Emotional Experience (Neu0)

```{r echo=FALSE, warning=FALSE}
p1 = ggplot(baselinecov, aes(x=Sex, y=Neu0, fill=Sex)) + 
        geom_boxplot() + guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)
p2 = ggplot(baselinecov, aes(x=Cohort, y=Neu0, fill=Cohort)) + 
        geom_boxplot() + guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)
p3 = ggplot(baselinecov, aes(x=Age, y=Neu0, fill=Age)) + 
        geom_boxplot() + guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)
p4 = ggplot(baselinecov, aes(x=Ethnicity, y=Neu0, fill=Ethnicity)) + 
        geom_boxplot() + guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)
multiplot(p1, p2, p3, p4, cols=2)
```

----

```{r echo=FALSE, warning=FALSE}
p1 = ggplot(baselinecov, aes(x=Specialty, y=Neu0, fill=Specialty)) + 
        geom_boxplot() + guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2) +
        theme(axis.text.x = element_text(angle = txt.angle))
p2 = ggplot(baselinecov, aes(x=Marital, y=Neu0, fill=Marital)) + 
        geom_boxplot() + guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)
p3 = ggplot(baselinecov, aes(x=Child, y=Neu0, fill=Child)) + 
        geom_boxplot() + guides(fill=FALSE) +
        stat_summary(fun.y=mean, geom="point", shape=5, size=2)

pushViewport(viewport(layout = grid.layout(2, 2)))  
print(p2, vp = viewport(layout.pos.row = 1, layout.pos.col = 1))     
print(p3, vp = viewport(layout.pos.row = 1, layout.pos.col = 2))     
print(p1, vp = viewport(layout.pos.row = 2, layout.pos.col = 1:2))
```


```{r, include=FALSE}
## prepares data for making Global Methylation Correlation Plots

uniq.ids <- unique(autox.sub.both.long$id)

# compute correlations
correlations <- rep(0, length(uniq.ids))
names(correlations) = uniq.ids
for (elt in uniq.ids){
        x <- with(autox.sub.both.long, methyl[id == elt & visit=="v1"])
        y <- with(autox.sub.both.long, methyl[id == elt & visit=="v2"])
        correlations[as.character(elt)] <- 
                cor(x, y, use="complete.obs", method="spearman")
}
# define a function to get plots
get_plt = function(idx) {
        elt = uniq.ids[idx]
        correl = correlations[idx]
        x <- with(autox.sub.both.long, methyl[id == elt & visit=="v1"])
        y <- with(autox.sub.both.long, methyl[id == elt & visit=="v2"])
        df <- as.data.frame(cbind(x,y))
        
        mytitle <- paste("subj", elt, "cor =", round(correl, 2))        
        p <- ggplot(df, aes(x, y)) + geom_point() + 
                labs(x="Visit 1", y="Visit 2", title=mytitle)
}
```

## Global Methylation Correlation Plots

```{r, echo=FALSE, fig.width=8, fig.height=4, warning=FALSE, message=FALSE}
p5 = get_plt(5)
p31 = get_plt(31)
multiplot(p5, p31, cols=2)
```

